### ISSUE TITLE
Error with augeas

### ISSUE THREAD

**Issue by nieldm** [mjhas/mailserver#1]
Hi,

I already install de augeas-lenses and libaugeas-ruby and im getting this error:

```
err: /Stage[main]/Mailserver/Postfix::Config::Mastercf[smtp]/Augeas[postfix master.cf smtp]: Could not evaluate: Error sending command 'set' with params ["/files/etc/postfix/master.cf/smtp/type", "inet"]/Error sending command 'set' with params ["/files/etc/postfix/master.cf/smtp/type", "inet"]
```

**Comment by nieldm** [comment]
i kind of solved, just comment the lines 184 to 188 at the mailserver/manifest/init.pp

```
postfix::config::mastercf { 'smtp':
    type         => 'inet',
    unprivileged => 'n',
    command      => '"smtpd"'
  }
```

because its fail when it tries to set that configuration, i dont know if this its a normal bug or its just me!, but thats how i solved

**Comment by mjhas** [comment]
hi,
   can you run puppet with --debug and show me the specific output (for augeas or the failed part).  Does augeas fail or the service startup of postfix?  

Other helpful things:
- Operating system release/version
- your /etc/postfix/master.cf config
- The output of `dpkg --list | grep -E 'augeas|ruby|puppet'` 

I just tried on debian 7.1/2 and it worked for me. 

best regards, michael

**Comment by mjhas** [comment]
closing this issue for now until further information is available
