### ISSUE TITLE
Using the components separately

### ISSUE THREAD

**Issue by andyleejordan** [mjhas/mailserver#2]
I've been working on setting up my own mail server using Postfix and Dovecot, and this module is _close_ to what I need. However, I don't need virtual users, and already manage a Postgres server using the Puppetlabs module, which would conflict with this.

I think I can get a working set up by using your Postfix, Dovecot, ClamAV, and AMaViS modules directly. I've been looking through this module's `init.pp` manifest though and noticed a few uses of `postfix::config::mastercf` that seems to me to pass options to `stmpd`. I've been following [this guide](http://dbpmail.net/essays/2013-06-29-hackers-replacement-for-gmail.html) and [this guide](https://www.digitalocean.com/community/articles/how-to-set-up-a-postfix-e-mail-server-with-dovecot), which both set options in that manner. Do you have any advice on what I would need for a single user server? It would be _nice_ to have SMTP for my phone, but I'd primarily like to use `notmuch` over ssh, which would be running as the Unix user on the mail server.

**Comment by andyleejordan** [comment]
So far I know I need to include these classes:

``` yaml
classes:
  - amavis
  - clamav
  - dovecot
  - dovecot::auth
  - dovecot::base
  - dovecot::ida
  - dovecot::imap
  - dovecot::mail
  - dovecot::master
  - dovecot::ssl
  - postfix
  - postfix::config
```

With these settings for Dovecot:

``` yaml
dovecot::auth::disable_plaintext_auth: 'yes'
dovecot::auth::auth_mechanisms: 'login cram-md5'
dovecot::mail::mailstorepath: '~/mail'
dovecot::master::postfix: true
dovecot::ssl::ssl: 'yes'
dovecot::ssl::ssl_certfile: '/etc/ssl/certs/schwartzmeyer.com.crt'
dovecot::ssl::ssl_keyfile: '/etc/ssl/private/schwartzmeyer.com.key'
dovecot::ssl::ssl_ca: '/etc/ssl/certs/ca-certificates.crt'
```

And these for Postfix:

``` yaml
postfix::config::content_filter: 'amavis:[127.0.0.1]:10024'
postfix::config::home_mailbox: 'mail/'
postfix::config::mydestination: '$myhostname, localhost.$mydomain, localhost, $mydomain'
postfix::config::myorigin: '$mydomain'
postfix::config::mynetworks: '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128'
postfix::config::smtpd_recipient_restrictions: 'permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_unknown_sender_domain'
postfix::config::smtpd_sasl_auth_enable: 'yes'
postfix::config::smtpd_sasl_local_domain: '$myhostname'
postfix::config::smtpd_sasl_security_options: 'noanonymous'
postfix::config::smtpd_sender_restrictions: 'permit_sasl_authenticated, permit_mynetworks'
postfix::config::smtpd_tls_auth_only: 'no'
postfix::config::smtpd_tls_cert_file: '/etc/ssl/certs/schwartzmeyer.com.crt'
postfix::config::smtpd_tls_key_file: '/etc/ssl/private/schwartzmeyer.com.key'
postfix::config::smtpd_tls_loglevel: '1'
postfix::config::smtpd_tls_received_header: 'yes'
postfix::config::smtpd_tls_session_cache_timeout: '3600s'
postfix::config::smtpd_use_tls: 'yes'
postfix::config::smtpd_sasl_type: 'dovecot'
postfix::config::smtpd_sasl_path: 'private/auth'
```

ClamAV and AMaViS don't need _necessarily_ need parameters it seems. (There is a dependency; is it necessary or just makes the first installation clean?) However, I may want to model after this module's:

``` puppet
class { 'amavis::config':
    bypass_virus_checks_maps => '(\%bypass_virus_checks, \@bypass_virus_checks_acl, \$bypass_virus_checks_re);',
    bypass_spam_checks_maps  => '(\%bypass_spam_checks, \@bypass_spam_checks_acl, \$bypass_spam_checks_re);',
    final_virus_destiny      => 'D_REJECT; # (defaults to D_BOUNCE)',
    final_banned_destiny     => 'D_REJECT;  # (defaults to D_BOUNCE)',
    final_spam_destiny       => 'D_PASS;  # (defaults to D_REJECT)',
    final_bad_header_destiny => 'D_PASS;  # (defaults to D_PASS), D_BOUNCE suggested',
  }
```

The `smtpd` commands in the `postfix::config::mastercf` resources confuse me; can't these settings all just be set in Postfix?

**Comment by andyleejordan** [comment]
Also, I guess `dovecot::sieve` is used with LDA, but is it necessary?

**Comment by andyleejordan** [comment]
Oooh, so at least the `postfix::config::mastercf` resources that add lines like `smtp <options>` and `smtpd <options>` set up multiple processes doing different things with different options, hence the override. Well, now to figure out which ones I need.

**Comment by andyleejordan** [comment]
So it is totally doable and seems to be working. I need to test it quite a bit more before moving my mail over to it (also need to get offlineimap setup). The configuration as of now is in my [puppet-manifests repository](https://github.com/andschwa/puppet-manifests/blob/master/hiera/nodes/krikkit.yaml#L180-L259).

Any advice would be greatly appreciated :) Thanks for all the hard work you put into these modules.

**Comment by mjhas** [comment]
well, looks fine with me. as you already figured it out. 
@dovecot sieve it should not be necessary
@regarding postgres, I guess this is a version conflict because you are using the newer version of puppetlabs/postgres, right?

**Comment by andyleejordan** [comment]
Actually looking at the code Postgres probably wouldn't conflict, but I just don't need it (yet), being single-user. This [module](https://github.com/wyrie/puppet-spamassassin) looks really promising for just `spamassassin`.

**Comment by andyleejordan** [comment]
Well it's been fun. Finally got it all working. There were a few kinks to work out, mostly I think because this module was developed specifically for using virtual users (which is great, I was just going a different route), and as such Dovecot had to be re-tweaked to allow PAM authentication for system users (there's a PR enabling this now). I went back to using your AMaViS module, and set it up by following their readme very carefully, testing every step of the way. I don't know what went wrong with the original implementation, but it's tested and working now. I have IMAP and SMTP over SSL working with Dovecot, and anti-spam through AMaViS and Spamassassin working as well, all of course with Postfix delivering to my local Maildir. With this all setup, I can use notmuch over ssh, or IMAP from my phone. Thanks for your modules man!

**Comment by mjhas** [comment]
I prepared something, maybe you would like to put in your config in the else tree. So that people can enjoy your configuration with this module.

**Comment by andyleejordan** [comment]
Yeah! I could toss something in there. Gonna finish with finals week first. Ack.

**Comment by mjhas** [comment]
good luck with your finals!

**Comment by andyleejordan** [comment]
@mjhas A much belated thanks! They went well, and my summer internship is going splendidly :) I'll add this this issue to my to-do list.

**Comment by Routhinator** [comment]
@mjhas did you ever push your config? I'm interested as I want postgres on a dedicated server and a config that uses ldap and multiple domains. Yours sounds like a good start.

**Comment by mjhas** [comment]
@Routhinator sorry, I never had the time to finish it or even get it started as I have no need for this separation. However you should be able to use the modules separately anyway.  Just apply the parts of the config you need on the nodes you need.

**Comment by andyleejordan** [comment]
@mjhas It's okay, I never did either. But my finals went well (years ago)! Thanks 😄
