### ISSUE TITLE
External SMTP not functioning correctly.

### ISSUE THREAD

**Issue by Nekroze** [mjhas/mailserver#5]
Hi, Love the module but i am having some problems here.

I cannot connect to the servers smtp on port 587, 465, or even 25 externally.

I must be missing something. I can connect fine to port 25 internally and the imap ports 143 and 993 are working fine externally.

Does the resulting mail server require any special things setup or taken into consideration to use SMTP externally?

I really appreciate any assistance you could provide.

**Comment by mjhas** [comment]
HI, can you give me a few more hints. Where are you running your postfix service? E.g. at home? Typically a lot of ISP block SMTP access from external networks to avoid being flagged as spammer.

**Comment by Nekroze** [comment]
Hi @mjhas 

I am running this at home however my ISP does allow SMTP externally as I have had a working email server in the past but it wasn't puppet managed.

Here is my current manifest for the server:

```
file { '/etc/dovecot/conf.d/mx.nekroze.com.key':
  source => 'puppet:///files/certs/mx.nekroze.com.key',
}
file { '/etc/dovecot/conf.d/mx.nekroze.com.crt':
  source => 'puppet:///files/certs/mx.nekroze.com.crt',
}
class { 'mailserver':
  mydestination         => 'mx.nekroze.com',
  myhostname            => 'mx.nekroze.com',
  smtpd_banner_hostname => 'mx.nekroze.com',
  ssl_key_file          => 'mx.nekroze.com.key',
  ssl_cert_file         => 'mx.nekroze.com.crt',
  dbpassword            => 'XXXXXXXXXXXX',
  dbuser                => 'mail',
  domains               => ['nekroze.com'],
  postmaster_address    => 'postmaster@nekroze.com',
  users                 => {
    'tlawson@nekroze.com' => {
      password => 'XXXXXX',
    },
  },
  forwards              => {                                                                                                                
    'taylor@nekroze.com'     => { destination => 'tlawson@nekroze.com' },
    'admin@nekroze.com'      => { destination => 'tlawson@nekroze.com' },
    'support@nekroze.com'    => { destination => 'admin@nekroze.com' },
    'abuse@nekroze.com'    => { destination => 'admin@nekroze.com' },
    'postmaster@nekroze.com' => { destination => 'admin@nekroze.com' },
  },                                                                                                                                       
}
```

This is running on centos 6.5.

Please let me know if you require any further information.

Thanks for the response.

**Comment by mjhas** [comment]
hey sorry for the late reply, can you check your syslog/mail.log for problems? normally postfix writes a lot of messages into the log after it is started.

**Comment by Nekroze** [comment]
Hi @mjhas,

Unfortunately i could not await response and decided to use a different email system. As such i can provide no more information and will close this issue.

Thanks for your time.
