### ISSUE TITLE
Usage from hiera

### ISSUE THREAD

**Issue by DeaconDesperado** [mjhas/mailserver#6]
I'm wondering if it's possible to use the resources `mailuser` and `mailforward` directly with `create_resources` in hiera?

I'm trying to define the mailserver params with hiera and using create_resources to set up the sql statement parts:

hiera:

```
classes:
  - mailserver
  - gnmail

mailserver::ssl_key_file : '/etc/ssl/private/ssl-cert-snakeoil.key'
mailserver::ssl_cert_file : '/etc/ssl/certs/ssl-cert-snakeoil.pem'
mailserver::dbpassword : 'emailonly'
mailserver::dbuser : 'smtp'
mailserver::domains : ["%{::fqdn}"]
gnmail::users:
  root@domain.com:
    password: "foob"
    quota: 100000
gnmail::forwards: {}
```

Shim class for create_resources

```
class gnmail(
  $users = {},
  $forwards = {}
){
  create_resources(mailserver::mailuser, $users)
  create_resources(mailserver::mailforwards, $forwards)
}
```

However, puppet seems unable to find the mailuser and mailforwards defined types despite their inclusion in the module path.  Is this because they would need to be namespaced?

**Comment by mjhas** [comment]
Hi,
   you definitely should namespace them. Newer version of puppet can be quite strict about that. Can you give me the exact error message? Also can you try and see if actually using mailserver:users and mailserver::forwards work? 

best regards, michael

**Comment by DeaconDesperado** [comment]
Error is:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid resource type mailserver::mailuser at /srv/puppet/modules/gnmail/manifests/init.pp:7
```

Will try direct resources and post results.  Thanks!

**Comment by DeaconDesperado** [comment]
Using the classes directly results with:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type mailforwards at /srv/puppet/environments/production/site/mailserver/manifests/mailuser.pp:8
```

I'm using puppet environments if that's relevant.

Is it possible the defined types for forwards and user need to be specified with namespaces in the module? like:

```
define mailserver::mailuser(
  ...args
)
```

**Comment by mjhas** [comment]
of course they should also have the namespaces included. Does this fix the issue for you?

**Comment by DeaconDesperado** [comment]
It appears it does!  Pull request inbound.

**Comment by mjhas** [comment]
nice ;)
